name: Lint Helm chart
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Lint grafana-agent
        run: helm lint ./charts/grafana-agent
