apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
data:
  {{- if .Values.config }}
  config.river: {{ toYaml .Values.config | indent 2 }}
  {{- else }}
  config.river: |- {{ .Files.Get "config/example.river" | nindent 4 }}
  {{- end }}
