{{- if eq .Values.controller.type "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  minReadySeconds: 10
  selector:
    matchLabels:
      {{- include "grafana-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grafana-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "grafana-agent.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- include "grafana-agent.container" . | nindent 8 }}
        {{- include "grafana-agent.watch-container" . | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "grafana-agent.fullname" . }}
        {{- if .Values.agent.mounts.varlog }}
        - name: varlog
          hostPath:
            path: /var/log
        {{- end }}
        {{- if .Values.agent.mounts.dockercontainers }}
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/containers
        {{- end }}
        {{- range .Values.controller.volumes.extra }}
        - {{ toYaml . | nindent 10 }}
        {{- end }}
  {{- with .Values.controller.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
